### ISSUE TITLE
question about volumes

### ISSUE THREAD

**Issue by mcinnes01** [mp-se/fermentrack-docker#16]
Hi,

I've been porting this in to a home assistant addon, essentially allowing me to run fermentrack as an addon within my home automation system.

Home assistant addons have certain conventions to adhere to and one of them is that you get a set mount-point to persist data from your container.

In this instance we get a "/data" bind-mount in the docker container. As this isn't a volume I can't make a symlink to the locations you specify in "/home/fermentrack/fermentrack/db" etc.

I just wondered if it would be possible to have the following folders inside my "/data" folder instead.

So my plan would be to change the following:

/home/fermentrack/fermentrack/data >> /data/fermentrack/data
/home/fermentrack/fermentrack/db  >> /data/fermentrack/db
/home/fermentrack/fermentrack/log  >> /data/fermentrack/log

I'm not too hot on nginx or fermentracks architecture so I'm not sure how I can change these paths without changing fermentrack itself.

I guess changing the entire python env to /data/fermentrack isn't what I want as it means all the application files will be on the home automation server, but I do want the data, log and db directories.

If you are able to give me some guidance here is what I've got so far: https://github.com/mcinnes01/addon-fermentrack/

Many thanks

Andy

**Comment by mp-se** [comment]
I'm not sure your approach is that easy or even feasable. Running it as an add-on would require that you have it installed in the same environment as HA which include django and more... Have you seen any other add-on built this way? I think you approach would require a substansial rewrite of fermentrack. and proably break all the lovelace principles as well. 

A better apporoach would probably be to integrate the two like with node-red. I've used fermentrack push with node-red to get my values pushed to HA. 

Controlling fermentrack is not as easy since there are no real REST-API's available (the API's are only internal today). Another option would be to include fermentrack as a iframe which has been discussed in the fermentrack repo.  It requires that you disable a security feature in django

**Comment by mp-se** [comment]
I guess your option would be to run it in the same way as node-red addon which would basically require you to change to one of the base images that is provided by home assistant. That is probably feasable but you still need to figure out and handle the integration between fermentrack and HA. Even node red has an addon for integrating with home assistant so that entities can be updated etc. 

I dont really see what benefits this would bring other that it's installable via home assistant?

**Comment by mp-se** [comment]
On your question about fermentrack directories,

The db directory can be changed in the fermentrack_django/setting.py file but the others I'm no so sure if there is one place you can change them, probably requires some changes to the code. You probably need to dig into the code to see how that is done.

I choose not to change anything in the standard installations since that would require that I maintain my own fork of fermentrack which is not what i want to do. My apporach has been to have no changes to the codebase and fix things in the image. 

If there are specific rules in HA that you need to have it in a specific way you probably need to have your own fork of fermentrack as well to be compliant.

**Comment by mcinnes01** [comment]
I've managed to get it to run as a hassio addon, so it's basically a docker container that has a little plumbing through hassio to allow it to be installed and managed within home assistant. In this regard it's entirely isolated from home assistant and home assistant acts as a hypervisor, or basically controls docker on the host system.

I have it running, and it seems to work using the hassio debian base image, I've even managed to figure out the permissions to give the container enough privilege to access the usb devices.

The only bit I haven't figured is getting the directory structure aligned with "/data" folder that hassio gives as a bind-mount to the host file system for persisting data.

I too was trying to avoid changing the fermentrack code base so that I can still enable updates to be performed within fermentrack. I remember reading one of the key things you pointed out was this:

> Database file (db.sqlite3) is moved to a subdirectory called /home/fermentrack/fermetrack/db in order to have a volume mount point (this is done since docker is not really good at handling a single file outside the container) which would be the case if the database file wasnt moved.

Did this require a change to fermentrack or is this just a change to the installation of fermentrack within the container?

Also where was the db file stored originally and did the other directories such as /home/fermentrack/fermentrack/data and /home/fermentrack/fermentrack/log already exist where they are or is the an entirely new subdirectory structure to enable persistence to be easier with docker?

Finally if moving the last 2 things isn't possible without changing code, I guess losing the logs I can live with as I still have stdout and stderr from docker, but is there anything fundamental stored in data that would affect the operation of fermentrack if the container was stopped and started?

Thank you so much for taking the time to answer my questions :)

P.s. if you are a HA user you can try my addon by adding my repository to the addon store in hassio:
https://github.com/mcinnes01/addon-fermentrack/

Feedback much appreciated

**Comment by mp-se** [comment]
Changing the db folder required a change of fermentrack so you can check that PR which i submitted.

The data folder stores all fermentation logs so that is quite central for the functionallity. Changing that would require a code change in fermentrack as well as the debug logs.

**Comment by mcinnes01** [comment]
Ok cool thanks, I'll see if I can find it to see what is involved :)
